/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0             (GUI_ID_USER + 0x00)
#define ID_TEXT_0             (GUI_ID_USER + 0x01)
#define ID_TEXT_1             (GUI_ID_USER + 0x02)
#define ID_TEXT_2             (GUI_ID_USER + 0x03)
#define ID_TEXT_3             (GUI_ID_USER + 0x04)
#define ID_TEXT_4             (GUI_ID_USER + 0x05)
#define ID_TEXT_5             (GUI_ID_USER + 0x06)
#define ID_TEXT_6             (GUI_ID_USER + 0x07)
#define ID_TEXT_7             (GUI_ID_USER + 0x08)
#define ID_BUTTON_0             (GUI_ID_USER + 0x09)
#define ID_BUTTON_1             (GUI_ID_USER + 0x0A)
#define ID_BUTTON_2             (GUI_ID_USER + 0x0B)
#define ID_BUTTON_3             (GUI_ID_USER + 0x0C)
#define ID_EDIT_0             (GUI_ID_USER + 0x0D)
#define ID_EDIT_1             (GUI_ID_USER + 0x0E)
#define ID_EDIT_2             (GUI_ID_USER + 0x0F)
#define ID_EDIT_3             (GUI_ID_USER + 0x10)
#define ID_EDIT_4             (GUI_ID_USER + 0x11)
#define ID_EDIT_5             (GUI_ID_USER + 0x12)
#define ID_EDIT_6             (GUI_ID_USER + 0x13)
#define ID_EDIT_7             (GUI_ID_USER + 0x14)
#define ID_TEXT_8             (GUI_ID_USER + 0x15)
#define ID_TEXT_9             (GUI_ID_USER + 0x16)
#define ID_EDIT_8             (GUI_ID_USER + 0x17)
#define ID_LISTBOX_0 (GUI_ID_USER + 0x18)


// USER START (Optionally insert additional defines)

#define WINDOWS_BACK_COLOUR (0Xbdfb86)
#include "include.h"
#include "save_data.h"
#include "protocol.h"
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)

void disable_button_save(void)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(parameter_window, ID_BUTTON_2);
    WM_DisableWindow(hItem);
}

void enable_button_save(void)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(parameter_window, ID_BUTTON_2);
    WM_EnableWindow(hItem);
}

void disable_set_parameter(void)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_0);
    WM_DisableWindow(hItem);
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_1);
    WM_DisableWindow(hItem);
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_2);
    WM_DisableWindow(hItem);
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_3);
    WM_DisableWindow(hItem);
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_4);
    WM_DisableWindow(hItem);
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_5);
    WM_DisableWindow(hItem);
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_6);
    WM_DisableWindow(hItem);
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_7);
    WM_DisableWindow(hItem);
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_8);
    WM_DisableWindow(hItem);
}
void enable_set_parameter(void)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_0);
    WM_EnableWindow(hItem);
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_1);
    WM_EnableWindow(hItem);
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_2);
    WM_EnableWindow(hItem);
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_3);
    WM_EnableWindow(hItem);
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_4);
    WM_EnableWindow(hItem);
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_5);
    WM_EnableWindow(hItem);
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_6);
    WM_EnableWindow(hItem);
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_7);
    WM_EnableWindow(hItem);
    hItem = WM_GetDialogItem(parameter_window, ID_EDIT_8);
    WM_EnableWindow(hItem);
}

void show_save_parameter(P_S_Parameter_Info beer)
{
	WM_HWIN hItem;
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_0);
	EDIT_SetDecMode(hItem,beer->tanghua_temperature_max,beer->tanghua_temperature_max,beer->tanghua_temperature_max,0,0);
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_1);
	EDIT_SetDecMode(hItem,beer->tanghua_temperature_min,beer->tanghua_temperature_min,beer->tanghua_temperature_min,0,0);
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_2);
	EDIT_SetDecMode(hItem,beer->tanghua_time,beer->tanghua_time,beer->tanghua_time,0,0);
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_3);
	EDIT_SetDecMode(hItem,beer->first_add_time,beer->first_add_time,beer->first_add_time,0,0);
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_4);
	EDIT_SetDecMode(hItem,beer->second_add_time,beer->second_add_time,beer->second_add_time,0,0);
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_5);
	EDIT_SetDecMode(hItem,beer->third_add_time,beer->third_add_time,beer->third_add_time,0,0);
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_6);
	EDIT_SetDecMode(hItem,beer->add_coagulant_time,beer->add_coagulant_time,beer->add_coagulant_time,0,0);
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_7);
	EDIT_SetDecMode(hItem,beer->boil_time,beer->boil_time,beer->boil_time,0,0);
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_8);
	EDIT_SetDecMode(hItem,beer->wash_volume,beer->wash_volume,beer->wash_volume,0,0);
}

void save_parameter_to_rom(P_S_Parameter_Info beer)
{
	WM_HWIN hItem;
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_0);
	beer->tanghua_temperature_max = EDIT_GetValue(hItem);
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_1);
	beer->tanghua_temperature_min= EDIT_GetValue(hItem);
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_2);
	beer->tanghua_time= EDIT_GetValue(hItem);
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_3);
	beer->first_add_time= EDIT_GetValue(hItem);
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_4);
	beer->second_add_time= EDIT_GetValue(hItem);
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_5);
	beer->third_add_time= EDIT_GetValue(hItem);
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_6);
	beer->add_coagulant_time= EDIT_GetValue(hItem);
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_7);
	beer->boil_time= EDIT_GetValue(hItem);
	hItem = WM_GetDialogItem(parameter_window, ID_EDIT_8);
	beer->wash_volume= EDIT_GetValue(hItem);
	save_machine_info();
}

void show_parameter_window(void)
{
	WM_HWIN hItem;
	WM_HideWindow(window);
	WM_ShowWindow(parameter_window);	
	hItem = WM_GetDialogItem(parameter_window, ID_LISTBOX_0);
	show_save_parameter(&(machine_info.beer[LISTBOX_GetSel(hItem)]));
}


// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "parameter_Seting", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text_tanghua_max", ID_TEXT_0, 30, 25, 300, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_tanghua_min", ID_TEXT_1, 30, 75, 300, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_tanghua_time", ID_TEXT_2, 30, 125, 300, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_2nd_add_time", ID_TEXT_3, 30, 175, 300, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_2nd_add_time", ID_TEXT_4, 30, 224, 300, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_3th_add_time", ID_TEXT_5, 30, 275, 300, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_add_nimgguji_time", ID_TEXT_6, 30, 325, 300, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_boil_time", ID_TEXT_7, 30, 375, 300, 30, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button_start", ID_BUTTON_0, 660, 345, 120, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button_cannel", ID_BUTTON_1, 500, 345, 120, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button_save", ID_BUTTON_2, 580, 265, 120, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button_seting", ID_BUTTON_3, 580, 185, 120, 50, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit_tanghua_max", ID_EDIT_0, 360, 25, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_tanghua_min", ID_EDIT_1, 360, 75, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_tanghua_time", ID_EDIT_2, 360, 125, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_1st_add_time", ID_EDIT_3, 360, 175, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_2nd_add_time", ID_EDIT_4, 360, 225, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_3th_add_time", ID_EDIT_5, 360, 275, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_add_ningguji_time", ID_EDIT_6, 360, 325, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_boil_time", ID_EDIT_7, 360, 375, 80, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_tips", ID_TEXT_8, 575, 426, 189, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_wash_sink", ID_TEXT_9, 30, 425, 300, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_wash_sink", ID_EDIT_8, 360, 425, 80, 30, 0, 0x64, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 520, 35, 240, 125, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
void display_value_on_edit(int value,unsigned char edit_cursor)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(parameter_window, (ID_EDIT_0-1+edit_cursor));
    /*switch(edit_cursor)
    {
        case 1:
            hItem = WM_GetDialogItem(parameter_window, ID_EDIT_0);
        break;

        case 2:
            hItem = WM_GetDialogItem(parameter_window, ID_EDIT_1);
        break;

        case 3:
            hItem = WM_GetDialogItem(parameter_window, ID_EDIT_2);
        break;

        case 4:
            hItem = WM_GetDialogItem(parameter_window, ID_EDIT_3);
        break;

        case 5:
            hItem = WM_GetDialogItem(parameter_window, ID_EDIT_4);
        break;

        case 6:
            hItem = WM_GetDialogItem(parameter_window, ID_EDIT_5);
        break;

        case 7:
            hItem = WM_GetDialogItem(parameter_window, ID_EDIT_6);
        break;

        case 8:
            hItem = WM_GetDialogItem(parameter_window, ID_EDIT_7);
        break;

        case 9:
        break;

        case 10:
        break;

    }*/
    EDIT_SetDecMode(hItem,value,value,value,0,0);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'parameter_Seting'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, (0x00BDFB86));
    //
    // Initialization of 'Text_tanghua_max'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "最高糖化温度(摄氏度)");
    TEXT_SetFont(hItem, HZ24_24);
    //
    // Initialization of 'Text_tanghua_min'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, HZ24_24);
    TEXT_SetText(hItem, "最低糖化温度(摄氏度)");
    //
    // Initialization of 'Text_tanghua_time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, HZ24_24);
    TEXT_SetText(hItem, "糖化时间(分钟)");
    //
    // Initialization of 'Text_2nd_add_time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, HZ24_24);
    TEXT_SetText(hItem, "第一次添加酒花时间(分钟)");
    //
    // Initialization of 'Text_2nd_add_time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetText(hItem, "第二次添加酒花时间(分钟)");
    TEXT_SetFont(hItem, HZ24_24);
    //
    // Initialization of 'Text_3th_add_time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetText(hItem, "第三次添加酒花时间(分钟)");
    TEXT_SetFont(hItem, HZ24_24);
    //
    // Initialization of 'Text_add_nimgguji_time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, HZ24_24);
    TEXT_SetText(hItem, "添加凝固剂时间(分钟)");
    //
    // Initialization of 'Text_boil_time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, HZ24_24);
    TEXT_SetText(hItem, "煮沸时间(分钟)");
    //
    // Initialization of 'Button_start'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, HZ24_24);
    BUTTON_SetText(hItem, "开始");
    //
    // Initialization of 'Button_cannel'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, HZ24_24);
    BUTTON_SetText(hItem, "取消");
    //
    // Initialization of 'Button_save'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, HZ24_24);
    BUTTON_SetText(hItem, "保存");
    //
    // Initialization of 'Button_seting'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, HZ24_24);
    BUTTON_SetText(hItem, "设置");
    //
    // Initialization of 'Edit_tanghua_max'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_20B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_tanghua_min'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_20B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_tanghua_time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_20B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_1st_add_time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_20B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_2nd_add_time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_20B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_3th_add_time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_20B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_add_ningguji_time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_20B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_boil_time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_20B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text_tips'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetText(hItem, "Smart Brewing beer");
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Text_wash_sink'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, HZ24_24);
    TEXT_SetText(hItem, "洗槽用水(升)");
    //
    // Initialization of 'Edit_wash_sink'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_20B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);

    LISTBOX_SetFont(hItem, HZ24_24);
    LISTBOX_AddString(hItem, "黑啤");
    LISTBOX_AddString(hItem, "波特");
    LISTBOX_AddString(hItem, "黄啤");
    LISTBOX_AddString(hItem, "小麦啤");
    LISTBOX_AddString(hItem, "自定义一");
    LISTBOX_AddString(hItem, "自定义二");
    LISTBOX_AddString(hItem, "自定义三");
    LISTBOX_AddString(hItem, "自定义四");
    // USER START (Optionally insert additional code for further widget initialization)
    LISTBOX_SetAutoScrollV(hItem,1);
    LISTBOX_SetScrollbarWidth(hItem,35);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    WM_DisableWindow(hItem);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    WM_DisableWindow(hItem);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    WM_DisableWindow(hItem);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    WM_DisableWindow(hItem);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    WM_DisableWindow(hItem);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    WM_DisableWindow(hItem);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
    WM_DisableWindow(hItem);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
    WM_DisableWindow(hItem);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
    WM_DisableWindow(hItem);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8);
    WM_DisableWindow(hItem);
    //diasble_button_save();
    //disable_set_parameter();

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button_start'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
         hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
        send_paratemer(LISTBOX_GetSel(hItem));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button_cannel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(parameter_window, ID_BUTTON_2);
    	WM_DisableWindow(hItem);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
	WM_DisableWindow(hItem);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
	WM_DisableWindow(hItem);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
	WM_DisableWindow(hItem);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
	WM_DisableWindow(hItem);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
	WM_DisableWindow(hItem);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
	WM_DisableWindow(hItem);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
	WM_DisableWindow(hItem);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
	WM_DisableWindow(hItem);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8);
	WM_DisableWindow(hItem);
        show_main_windows();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button_save'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
        save_parameter_to_rom(&(machine_info.beer[LISTBOX_GetSel(hItem)]));
        disable_button_save();
        disable_set_parameter();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button_seting'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        show_psw_dlg();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'Edit_tanghua_max'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        show_key_board("设置温度",2);
        Dlg_key_value.cur_cursor = 1;
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'Edit_tanghua_min'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        show_key_board("设置温度",2);
        Dlg_key_value.cur_cursor = 2;
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'Edit_tanghua_time'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        show_key_board("设置时间",3);
        Dlg_key_value.cur_cursor = 3;
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by 'Edit_1st_add_time'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        show_key_board("设置时间",3);
        Dlg_key_value.cur_cursor = 4;
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_4: // Notifications sent by 'Edit_2nd_add_time'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message
        show_key_board("设置时间",3);
        Dlg_key_value.cur_cursor = 5;
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_5: // Notifications sent by 'Edit_3th_add_time'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        show_key_board("设置时间",3);
        Dlg_key_value.cur_cursor = 6;
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_6: // Notifications sent by 'Edit_add_ningguji_time'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        show_key_board("设置时间",3);
        Dlg_key_value.cur_cursor = 7;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_7: // Notifications sent by 'Edit_boil_time'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        show_key_board("设置时间",3);
        Dlg_key_value.cur_cursor = 8;
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_8: // Notifications sent by 'Edit_wash_sink'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        show_key_board("设置水量",3);
        Dlg_key_value.cur_cursor = 11;
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        switch(LISTBOX_GetSel(hItem))
        {
            case 0:
		set_runing_window_beer_name("黑啤");
		show_save_parameter(&(machine_info.beer[0]));
            break;

            case 1:
                set_runing_window_beer_name("波特");
		show_save_parameter(&(machine_info.beer[1]));
            break;

            case 2:
                set_runing_window_beer_name("黄啤");
		show_save_parameter(&(machine_info.beer[2]));
            break;

            case 3:
                set_runing_window_beer_name("小麦啤");
		show_save_parameter(&(machine_info.beer[3]));
            break;

            case 4:
                set_runing_window_beer_name("自定义一");
		show_save_parameter(&(machine_info.beer[4]));
            break;

            case 5:
                set_runing_window_beer_name("自定义二");
		show_save_parameter(&(machine_info.beer[5]));
            break;

            case 6:
                set_runing_window_beer_name("自定义三");
		show_save_parameter(&(machine_info.beer[6]));
            break;

            case 7:
                set_runing_window_beer_name("自定义四");
		show_save_parameter(&(machine_info.beer[7]));
            break;
        }

        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createparameter_Seting
*/
WM_HWIN Createparameter_Seting(void);
WM_HWIN Createparameter_Seting(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)


// USER END

/*************************** End of file ****************************/
